language: node_js
node_js:
- '12.13'

install:
- yarn install

jobs:
  include:
  - stage: Test
    script: yarn test --watchAll=false -- --coverage && npx codecov
  - stage: Build
    script: yarn build

deploy:
  provider: npm
  email: carlosthe19916@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    branch: master
  skip_cleanup: true
  tag: next